d /var/cache/jellyfin 0775 tin tin -
d /var/lib/jellyfin 0775 tin tin -
d /var/log/jellyfin 0775 tin tin -
d /etc/jellyfin 0775 tin tin -
f /etc/jellyfin/jellyfin.env 0660 tin tin -
f /etc/jellyfin/logging.json 0660 tin tin -
