# SSH Latency & Performance Tuning
UseDNS no
GSSAPIAuthentication no
PubkeyAuthentication yes
TCPKeepAlive yes
ClientAliveInterval 15
ClientAliveCountMax 4
Compression no
IPQoS lowdelay throughput
AcceptEnv LANG LC_* TERM COLORTERM
