[Service]
Environment="LD_LIBRARY_PATH=/usr/lib/jvm/default/lib:/usr/lib/jvm/default-runtime/lib:/usr/lib64:/usr/lib:/var/lib/suwayomi/.local/share/Tachidesk/bin/kcef"
Environment="JAVA_TOOL_OPTIONS=-Djava.library.path=/usr/lib/jvm/default/lib:/usr/lib/jvm/default-runtime/lib:/usr/lib64:/usr/lib:/var/lib/suwayomi/.local/share/Tachidesk/bin/kcef"
